ajax/urls.py
from django.urls import path
from . import views

app_name='ajax'

urlpatterns =[
    path('', views.index, name="index"),
    path('search_wiki/', views.ajax, name="ajax"),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ajax/', include('ajax.urls')),
]

ajax/models.py
from django.db import models

# Create your models here.

ajax/views.py
from django.shortcuts import render
from django.http import HttpResponse
import simplejson as json
# Create your views here.
def index(request):

    return render(request, 'ajax/index.html')

def ajax(request):
    # request.POST.get('json형식 안의 내용') from html
    from_html_text = request.POST.get('text')
    print(from_html_text)

    context = {
        'text_return': 'aaaaa',
        'text_return2': '서버에서 보낸data',
    }
    
    return HttpResponse(json.dumps(context), 'ajax/index.html')

ajax/templates/ajax/index.html
{% extends 'base.html' %}
{% block body %}
<h1>ajax 예제</h1>
<input id="search_input" type="search" />
<button id="search_button" type="submit">클릭</button> <br>
서버에서 받을단어:<h1 id="h1-text">??</h1> <br>
검색한 단어:<h2 id="h2-text">??</h2>

<script>
    $('#search_button').click(function(){
        var text = $('#search_input').val()
        
        $.ajax({ 
            type: "POST", // 데이터를 전송type post/get
            url: "{% url 'ajax:ajax' %}", // 통신할 url을 지정
            data: {'text': text, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 서버로 데이터 전송시 옵션
            dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정, 없으면 알아서 판단
      
            success: function(data){ 
                //성공시 수행할 코드
                alert("통신성공");
                // alert(data);
                for(var i in data){
                    console.log(i)
                    $('#h1-text').html(data[i])
                }
                for(var i in data){
                    console.log(data[i])
                }
                $('#h2-text').html(text)
            },
            error: function(request, status, error){
                //통신 실패시 실행할 코드
                //window.location.replace("/accounts/login/")

            },
        }); //end ajax

    }) //end clickevent
    
</script>
{% endblock %}

config/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>